import type { Board } from '@/types';

export const BOARDS: Board[] = [
  {
    id: 'arduino-mega',
    name: 'Arduino MEGA 2560',
    mcu: 'ATmega2560',
    fcpu: 16_000_000,
    flashKB: 256,
    ramKB: 8,
    eepromKB: 4,
    icon: '🟦',
    builtinLed: 13,
    analogPins: [
      54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69,
    ],
    uartPins: [
      { tx: 1, rx: 0 },
      { tx: 18, rx: 19 },
      { tx: 16, rx: 17 },
      { tx: 14, rx: 15 },
    ],
    i2cPins: [{ sda: 20, scl: 21 }],
    spiPins: [{ mosi: 51, miso: 50, sck: 52, ss: 53 }],
    pins: [
      ...Array.from({ length: 54 }, (_, i) => ({
        number: i,
        label: `D${i}`,
        type: i < 14 ? 'digital' : ('analog' as const),
      })),
      ...Array.from({ length: 16 }, (_, i) => ({
        number: 54 + i,
        label: `A${i}`,
        type: 'analog' as const,
      })),
    ],
  },
  {
    id: 'arduino-uno',
    name: 'Arduino UNO R3',
    mcu: 'ATmega328P',
    fcpu: 16_000_000,
    flashKB: 32,
    ramKB: 2,
    eepromKB: 1,
    icon: '🟩',
    builtinLed: 13,
    analogPins: [14, 15, 16, 17, 18, 19],
    uartPins: [{ tx: 1, rx: 0 }],
    i2cPins: [{ sda: 18, scl: 19 }],
    spiPins: [{ mosi: 11, miso: 12, sck: 13, ss: 10 }],
    pins: [
      ...Array.from({ length: 14 }, (_, i) => ({
        number: i,
        label: `D${i}`,
        type: i < 14 ? 'digital' : ('analog' as const),
      })),
      ...Array.from({ length: 6 }, (_, i) => ({
        number: 14 + i,
        label: `A${i}`,
        type: 'analog' as const,
      })),
    ],
  },
  {
    id: 'arduino-nano',
    name: 'Arduino Nano',
    mcu: 'ATmega328P',
    fcpu: 16_000_000,
    flashKB: 32,
    ramKB: 2,
    eepromKB: 1,
    icon: '🟫',
    builtinLed: 13,
    analogPins: [14, 15, 16, 17, 18, 19, 20, 21],
    uartPins: [{ tx: 1, rx: 0 }],
    i2cPins: [{ sda: 18, scl: 19 }],
    spiPins: [{ mosi: 11, miso: 12, sck: 13, ss: 10 }],
    pins: [
      ...Array.from({ length: 14 }, (_, i) => ({
        number: i,
        label: `D${i}`,
        type: 'digital' as const,
      })),
      ...Array.from({ length: 8 }, (_, i) => ({
        number: 14 + i,
        label: `A${i}`,
        type: 'analog' as const,
      })),
    ],
  },
  {
    id: 'esp32',
    name: 'ESP32 DevKit',
    mcu: 'ESP32-D0WDQ6',
    fcpu: 240_000_000,
    flashKB: 4096,
    ramKB: 320,
    eepromKB: 0,
    icon: '🔴',
    builtinLed: 2,
    analogPins: [32, 33, 34, 35, 36, 39],
    uartPins: [
      { tx: 1, rx: 3 },
      { tx: 17, rx: 16 },
    ],
    i2cPins: [{ sda: 21, scl: 22 }],
    spiPins: [{ mosi: 23, miso: 19, sck: 18, ss: 5 }],
    pins: Array.from({ length: 40 }, (_, i) => ({
      number: i,
      label: `GPIO${i}`,
      type: 'digital' as const,
    })),
  },
  {
    id: 'esp8266',
    name: 'ESP8266 NodeMCU',
    mcu: 'ESP8266EX',
    fcpu: 80_000_000,
    flashKB: 4096,
    ramKB: 80,
    eepromKB: 0,
    icon: '🟠',
    builtinLed: 2,
    analogPins: [17],
    uartPins: [{ tx: 1, rx: 3 }],
    i2cPins: [{ sda: 4, scl: 5 }],
    spiPins: [{ mosi: 13, miso: 12, sck: 14, ss: 15 }],
    pins: Array.from({ length: 17 }, (_, i) => ({
      number: i,
      label: `D${i}`,
      type: 'digital' as const,
    })),
  },
  {
    id: 'rp2040',
    name: 'Raspberry Pi Pico',
    mcu: 'RP2040',
    fcpu: 133_000_000,
    flashKB: 2048,
    ramKB: 264,
    eepromKB: 0,
    icon: '🟢',
    builtinLed: 25,
    analogPins: [26, 27, 28, 29],
    uartPins: [
      { tx: 0, rx: 1 },
      { tx: 4, rx: 5 },
    ],
    i2cPins: [
      { sda: 4, scl: 5 },
      { sda: 6, scl: 7 },
    ],
    spiPins: [{ mosi: 3, miso: 4, sck: 2, ss: 5 }],
    pins: Array.from({ length: 30 }, (_, i) => ({
      number: i,
      label: `GP${i}`,
      type: 'digital' as const,
    })),
  },
];

export function getBoardById(id: string): Board | undefined {
  return BOARDS.find((b) => b.id === id);
}
